# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Yuzhu Sun
description: >- # this means to ignore newlines until "baseurl:"
  Yuzhu Sun github pages.
baseurl: "" # the subpath of the site
url: "https://yuzhus.github.io" # the base hostname & protocol for the site
og_image: /assets/img/yuzhu.jpg
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: Research
      slug: /research
    - name: Publications
      slug: /publications
    - name: Teaching
      slug: /teaching

footer:
  show_powered_by: true
  contact:
    - name: Email
      value: ysun32@qub.ac.uk
      link: mailto:ysun32@qub.ac.uk

  follow:
    - name: LinkedIn
      link: http://linkedin.com/in/yuzhu-sun-a8403b285
    - name: GitHub
      link: http://github.com/yuzhus

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
